### ISSUE TITLE
Model gives an error with empty package list

### ISSUE THREAD

**Issue by sara-02** [fabric8-analytics/f8a-hpf-insights#55]
Input:
```
[
    {
        "ecosystem": "maven",
        "package_list": []

    }
]
```
Output:
```
hpf-insights_1  | 2018-08-17 15:11:20,178 flask.app [ERROR] Exception on /api/v1/companion_recommendation [POST]
hpf-insights_1  | Traceback (most recent call last):
hpf-insights_1  |   File "/usr/lib64/python3.4/site-packages/flask/app.py", line 2292, in wsgi_app
hpf-insights_1  |     response = self.full_dispatch_request()
hpf-insights_1  |   File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1815, in full_dispatch_request
hpf-insights_1  |     rv = self.handle_user_exception(e)
hpf-insights_1  |   File "/usr/lib64/python3.4/site-packages/flask_cors/extension.py", line 161, in wrapped_function
hpf-insights_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
hpf-insights_1  |   File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1718, in handle_user_exception
hpf-insights_1  |     reraise(exc_type, exc_value, tb)
hpf-insights_1  |   File "/usr/lib64/python3.4/site-packages/flask/_compat.py", line 35, in reraise
hpf-insights_1  |     raise value
hpf-insights_1  |   File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1813, in full_dispatch_request
hpf-insights_1  |     rv = self.dispatch_request()
hpf-insights_1  |   File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1799, in dispatch_request
hpf-insights_1  |     return self.view_functions[rule.endpoint](**req.view_args)
hpf-insights_1  |   File "/src/flask_endpoint.py", line 92, in hpf_scoring
hpf-insights_1  |     input_stack['package_list'])
hpf-insights_1  |   File "/src/scoring/hpf_scoring.py", line 197, in predict
hpf-insights_1  |     if len(missing_packages) / len(input_stack) < UNKNOWN_PACKAGES_THRESHOLD:
hpf-insights_1  | ZeroDivisionError: division by zero


```

**Comment by sara-02** [comment]
Solution: Check for input_stack len before the check for known/unknown threshold
